version: "3.8"

services:
  # Face Attendance API
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
      - WORKERS=2
    volumes:
      - ./Silent_Face_Anti_Spoofing:/app/Silent_Face_Anti_Spoofing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Nginx reverse proxy (optional for local testing)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: unless-stopped
    profiles:
      - nginx # Use with: docker-compose --profile nginx up

  # MongoDB (for local development)
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    profiles:
      - mongodb # Use with: docker-compose --profile mongodb up

volumes:
  mongodb_data:
