services:
  - type: web
    name: face-attendance
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: face-attendance-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
